project:
  type: website
  output-dir: docs
  resources:
    - data/
  
  
website:
  title: "STA323"
  search: false
  navbar:
    background: "#2774AE" # nice blue -- Spring 2023
    left:
    - schedule.qmd
    - syllabus.qmd
    - links.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



