project:
  type: website
  output-dir: docs
  resources:
    - data/
    - scripts/
  render: 
    - "*.qmd"
    - "!/quizzes"
  
  
website:
  title: "STA323"
  search: false
  navbar:
    background: "#2774AE" # nice blue -- Spring 2023
    left:
    - href: schedule.qmd
      text: schedule
    - href: syllabus.qmd
      text: syllabus
    - href: project.qmd
      text: project
    - href: links.qmd
      text: links
    
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



